export const NOTE_ADD_REQUEST = "NOTE_ADD_REQUEST";
export const NOTE_ADD_SUCCESS = "NOTE_ADD_SUCCESS";
export const NOTE_ADD_FAIL = "NOTE_ADD_FAIL";


export const NOTE_UPDATE_REQUEST = 'NOTE_UPDATE_REQUEST';
export const NOTE_UPDATE_SUCCESS = 'NOTE_UPDATE_SUCCESS';
export const NOTE_UPDATE_FAIL = 'NOTE_UPDATE_FAIL';

